package com.study.jfinal.activerecord.domain;

import com.study.jfinal.activerecord.model.BaseUser;

/**
 * Generated by JFinal.
 * 充当MVC模式中的模型，包含数据库操作方法
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
